# config/settings.py 

ASSETS = ["SHAKTIPUMP.NS", "WABAG.NS","NATCOPHARM.NS","DLF.NS","SUNPHARMA.NS","SUZLON.NS"] 
PORTFOLIO_WEIGHTS = {"SHAKTIPUMP.NS": 0.67, "WABAG.NS": 0.17,"SUNPHARMA.NS": 0.03,"NATCOPHARM.NS": 0.07,"DLF.NS": 0.03,"SUZLON.NS": 0.03} 

START_DATE = "2023-01-01" 
END_DATE = "2026-01-05" 
CONFIDENCE_LEVELS = [0.95, 0.99]

# Time & Market Assumptions
TRADING_DAYS_PER_YEAR = 252

# Rolling Windows
ROLLING_VOL_WINDOW = 21
ROLLING_RETURN_WINDOW = 21

# Risk-Free Rate
RISK_FREE_RATE = 0  # annual

# Correlation Settings
CORRELATION_METHOD = "pearson"

# Drawdown
INITIAL_PORTFOLIO_VALUE = 1.0